/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Robert
 */
public class CharacterCreator extends javax.swing.JPanel {

    /**
     * Creates new form CharacterCreator
     */
    public CharacterCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        basicInfoPanel = new javax.swing.JPanel();
        characterNameField = new javax.swing.JTextField();
        characterClassBox = new javax.swing.JComboBox<>();
        characterClass = new javax.swing.JLabel();
        CharacterNameLabel = new javax.swing.JLabel();
        levelSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        conStatLabel = new javax.swing.JLabel();
        strStatLabel = new javax.swing.JLabel();
        dexStatLabel = new javax.swing.JLabel();
        wisStatLabel = new javax.swing.JLabel();
        intStatLevel = new javax.swing.JLabel();
        willStatLabel = new javax.swing.JLabel();
        totalPtsLabel = new javax.swing.JLabel();
        totalPtsRemainingValueLabel = new javax.swing.JLabel();
        totalPtsValuelabel1 = new javax.swing.JLabel();
        conSpinner = new javax.swing.JSpinner();
        strSpinner = new javax.swing.JSpinner();
        dexSpinner = new javax.swing.JSpinner();
        wisSpinner = new javax.swing.JSpinner();
        intSpinner = new javax.swing.JSpinner();
        wilSpinner = new javax.swing.JSpinner();
        characterSpritePreview = new javax.swing.JPanel();
        previousSpriteButton = new javax.swing.JButton();
        nextSpriteButton = new javax.swing.JButton();
        RandomSpriteButton = new javax.swing.JButton();
        characterSpriteCanvas = new java.awt.Canvas();
        AdvancedInfoPanel = new javax.swing.JPanel();
        hitPointsLabel = new javax.swing.JLabel();
        hpValueLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        speed_lightLoad = new javax.swing.JLabel();
        speed_mediumLoad = new javax.swing.JLabel();
        speed_heavyLoad = new javax.swing.JLabel();
        carryCapacityLabel = new javax.swing.JLabel();
        carry_overHead = new javax.swing.JLabel();
        carry_offGround = new javax.swing.JLabel();
        carry_pushDrag = new javax.swing.JLabel();
        instructionPanel = new javax.swing.JPanel();
        instructionsLabel = new javax.swing.JLabel();
        instructionTextPanel1 = new javax.swing.JScrollPane();
        instructionTextScrollArea = new javax.swing.JTextArea();
        finishCreationButton = new javax.swing.JButton();
        cancelCreationButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        basicInfoPanel.setBackground(new java.awt.Color(51, 51, 51));

        characterNameField.setText("[character name]");

        characterClassBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        characterClass.setForeground(new java.awt.Color(255, 255, 255));
        characterClass.setText("Class:");

        CharacterNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        CharacterNameLabel.setText("Name:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Level:");

        javax.swing.GroupLayout basicInfoPanelLayout = new javax.swing.GroupLayout(basicInfoPanel);
        basicInfoPanel.setLayout(basicInfoPanelLayout);
        basicInfoPanelLayout.setHorizontalGroup(
            basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(characterClass)
                    .addComponent(CharacterNameLabel))
                .addGap(18, 18, 18)
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basicInfoPanelLayout.createSequentialGroup()
                        .addComponent(characterClassBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(levelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        basicInfoPanelLayout.setVerticalGroup(
            basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CharacterNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterClassBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterClass)
                    .addComponent(levelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(basicInfoPanel, gridBagConstraints);

        statsPanel.setBackground(new java.awt.Color(204, 204, 204));

        conStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        conStatLabel.setText("Constitution");

        strStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        strStatLabel.setText("Strength");

        dexStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dexStatLabel.setText("Dexterity");

        wisStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wisStatLabel.setText("Wisdom");

        intStatLevel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        intStatLevel.setText("Intelligence");

        willStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        willStatLabel.setText("Willpower");

        totalPtsLabel.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        totalPtsLabel.setText("Total");

        totalPtsRemainingValueLabel.setText("[val]");
        totalPtsRemainingValueLabel.setToolTipText("Points left to distribute");

        totalPtsValuelabel1.setText("[val]");
        totalPtsValuelabel1.setToolTipText("Total points avaiable for distribution");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(conStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(strStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dexStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wisStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(intStatLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(willStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(totalPtsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(totalPtsRemainingValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wilSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPtsValuelabel1)
                    .addComponent(intSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wisSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conStatLabel)
                    .addComponent(conSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strStatLabel)
                    .addComponent(strSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dexStatLabel)
                    .addComponent(dexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wisStatLabel)
                    .addComponent(wisSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intStatLevel)
                    .addComponent(intSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(willStatLabel)
                    .addComponent(wilSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPtsLabel)
                    .addComponent(totalPtsRemainingValueLabel)
                    .addComponent(totalPtsValuelabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(statsPanel, gridBagConstraints);

        characterSpritePreview.setBackground(new java.awt.Color(204, 204, 204));

        previousSpriteButton.setText("Prev");
        previousSpriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousSpriteButtonActionPerformed(evt);
            }
        });

        nextSpriteButton.setText("Next");
        nextSpriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextSpriteButtonActionPerformed(evt);
            }
        });

        RandomSpriteButton.setText("Random");

        characterSpriteCanvas.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout characterSpritePreviewLayout = new javax.swing.GroupLayout(characterSpritePreview);
        characterSpritePreview.setLayout(characterSpritePreviewLayout);
        characterSpritePreviewLayout.setHorizontalGroup(
            characterSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(characterSpritePreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(characterSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterSpriteCanvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(characterSpritePreviewLayout.createSequentialGroup()
                        .addComponent(previousSpriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RandomSpriteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextSpriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        characterSpritePreviewLayout.setVerticalGroup(
            characterSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, characterSpritePreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterSpriteCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(characterSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousSpriteButton)
                    .addComponent(RandomSpriteButton)
                    .addComponent(nextSpriteButton))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(characterSpritePreview, gridBagConstraints);

        AdvancedInfoPanel.setBackground(new java.awt.Color(153, 153, 153));

        hitPointsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hitPointsLabel.setText("HP");

        hpValueLabel.setText("[val]");

        speedLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        speedLabel.setText("Speed");

        speed_lightLoad.setText("[val]");
        speed_lightLoad.setToolTipText("light load");

        speed_mediumLoad.setText("[val]");
        speed_mediumLoad.setToolTipText("medium load");

        speed_heavyLoad.setText("[val]");
        speed_heavyLoad.setToolTipText("heavy load");

        carryCapacityLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        carryCapacityLabel.setText("Carry");

        carry_overHead.setText("[val]");
        carry_overHead.setToolTipText("lift over head");

        carry_offGround.setText("[val]");
        carry_offGround.setToolTipText("lift off ground");

        carry_pushDrag.setText("[val]");
        carry_pushDrag.setToolTipText("push or drag");

        javax.swing.GroupLayout AdvancedInfoPanelLayout = new javax.swing.GroupLayout(AdvancedInfoPanel);
        AdvancedInfoPanel.setLayout(AdvancedInfoPanelLayout);
        AdvancedInfoPanelLayout.setHorizontalGroup(
            AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                        .addComponent(hitPointsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpValueLabel))
                    .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                        .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedLabel)
                            .addComponent(carryCapacityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                                .addComponent(carry_overHead)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carry_offGround)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carry_pushDrag))
                            .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                                .addComponent(speed_lightLoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speed_mediumLoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speed_heavyLoad)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdvancedInfoPanelLayout.setVerticalGroup(
            AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitPointsLabel)
                    .addComponent(hpValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLabel)
                    .addComponent(speed_lightLoad)
                    .addComponent(speed_mediumLoad)
                    .addComponent(speed_heavyLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carryCapacityLabel)
                    .addComponent(carry_overHead)
                    .addComponent(carry_offGround)
                    .addComponent(carry_pushDrag))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(AdvancedInfoPanel, gridBagConstraints);

        instructionPanel.setBackground(new java.awt.Color(103, 95, 66));

        instructionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        instructionsLabel.setText("Instructions");

        instructionTextPanel1.setBorder(null);

        instructionTextScrollArea.setEditable(false);
        instructionTextScrollArea.setBackground(new java.awt.Color(103, 96, 66));
        instructionTextScrollArea.setColumns(20);
        instructionTextScrollArea.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        instructionTextScrollArea.setForeground(new java.awt.Color(255, 255, 255));
        instructionTextScrollArea.setLineWrap(true);
        instructionTextScrollArea.setRows(5);
        instructionTextScrollArea.setText("this is the instruction area\n");
        instructionTextScrollArea.setWrapStyleWord(true);
        instructionTextScrollArea.setBorder(null);
        instructionTextScrollArea.setMargin(new java.awt.Insets(0, 0, 0, 0));
        instructionTextPanel1.setViewportView(instructionTextScrollArea);

        finishCreationButton.setText("Finish Creation");

        cancelCreationButton.setText("Cancel Creation");
        cancelCreationButton.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
				cancelCreationButtonActionPerformed(e);
			}
        });
        
        javax.swing.GroupLayout instructionPanelLayout = new javax.swing.GroupLayout(instructionPanel);
        instructionPanel.setLayout(instructionPanelLayout);
        instructionPanelLayout.setHorizontalGroup(
            instructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instructionPanelLayout.createSequentialGroup()
                        .addComponent(instructionsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(instructionTextPanel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelCreationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finishCreationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        instructionPanelLayout.setVerticalGroup(
            instructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finishCreationButton)
                .addGap(12, 12, 12)
                .addComponent(cancelCreationButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instructionPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(instructionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionTextPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(instructionPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void nextSpriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextSpriteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextSpriteButtonActionPerformed

    private void previousSpriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousSpriteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousSpriteButtonActionPerformed
    
    private void cancelCreationButtonActionPerformed(ActionEvent evt){
    	//return to the main menu when the cancel button is pressed
    	this.getParent().add(new MainMenu());
    	this.setVisible(false);
    	this.getParent().remove(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdvancedInfoPanel;
    private javax.swing.JLabel CharacterNameLabel;
    private javax.swing.JButton RandomSpriteButton;
    private javax.swing.JPanel basicInfoPanel;
    private javax.swing.JLabel carryCapacityLabel;
    private javax.swing.JLabel carry_offGround;
    private javax.swing.JLabel carry_overHead;
    private javax.swing.JLabel carry_pushDrag;
    private javax.swing.JLabel characterClass;
    private javax.swing.JComboBox<String> characterClassBox;
    private javax.swing.JTextField characterNameField;
    private java.awt.Canvas characterSpriteCanvas;
    private javax.swing.JPanel characterSpritePreview;
    private javax.swing.JSpinner conSpinner;
    private javax.swing.JLabel conStatLabel;
    private javax.swing.JSpinner dexSpinner;
    private javax.swing.JLabel dexStatLabel;
    private javax.swing.JLabel hitPointsLabel;
    private javax.swing.JLabel hpValueLabel;
    private javax.swing.JPanel instructionPanel;
    private javax.swing.JScrollPane instructionTextPanel1;
    private javax.swing.JTextArea instructionTextScrollArea;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JSpinner intSpinner;
    private javax.swing.JLabel intStatLevel;
    private javax.swing.JButton finishCreationButton;
    private javax.swing.JButton cancelCreationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner levelSpinner;
    private javax.swing.JButton nextSpriteButton;
    private javax.swing.JButton previousSpriteButton;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JLabel speed_heavyLoad;
    private javax.swing.JLabel speed_lightLoad;
    private javax.swing.JLabel speed_mediumLoad;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JSpinner strSpinner;
    private javax.swing.JLabel strStatLabel;
    private javax.swing.JLabel totalPtsLabel;
    private javax.swing.JLabel totalPtsRemainingValueLabel;
    private javax.swing.JLabel totalPtsValuelabel1;
    private javax.swing.JSpinner wilSpinner;
    private javax.swing.JLabel willStatLabel;
    private javax.swing.JSpinner wisSpinner;
    private javax.swing.JLabel wisStatLabel;
    // End of variables declaration//GEN-END:variables
}
