/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicstestbed;

/**
 *
 * @author Robert
 */
public class CharacterInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharacterInfoPanel
     */
    public CharacterInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statsPanel = new javax.swing.JPanel();
        conStatLabel = new javax.swing.JLabel();
        strStatLabel = new javax.swing.JLabel();
        dexStatLabel = new javax.swing.JLabel();
        wisStatLabel = new javax.swing.JLabel();
        intStatLevel = new javax.swing.JLabel();
        willStatLabel = new javax.swing.JLabel();
        conValueLabel = new javax.swing.JLabel();
        strValueLabel = new javax.swing.JLabel();
        dexValueLabel = new javax.swing.JLabel();
        wisValueLabel = new javax.swing.JLabel();
        intValueLabel = new javax.swing.JLabel();
        willValueLabel = new javax.swing.JLabel();
        AdvancedInfoPanel = new javax.swing.JPanel();
        hitPointsLabel = new javax.swing.JLabel();
        hpValueLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        speed_lightLoad = new javax.swing.JLabel();
        speed_mediumLoad = new javax.swing.JLabel();
        speed_heavyLoad = new javax.swing.JLabel();
        carryCapacityLabel = new javax.swing.JLabel();
        carry_overHead = new javax.swing.JLabel();
        carry_offGround = new javax.swing.JLabel();
        carry_pushDrag = new javax.swing.JLabel();
        hpMaxValueLabel = new javax.swing.JLabel();
        equipmentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inventoryPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        statsPanel.setBackground(new java.awt.Color(204, 204, 204));

        conStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        conStatLabel.setText("Constitution");

        strStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        strStatLabel.setText("Strength");

        dexStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dexStatLabel.setText("Dexterity");

        wisStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wisStatLabel.setText("Wisdom");

        intStatLevel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        intStatLevel.setText("Intelligence");

        willStatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        willStatLabel.setText("Willpower");

        conValueLabel.setText("[val]");

        strValueLabel.setText("[val]");

        dexValueLabel.setText("[val]");

        wisValueLabel.setText("[val]");

        intValueLabel.setText("[val]");

        willValueLabel.setText("[val]");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(strStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dexStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wisStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intStatLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(willStatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(willValueLabel)
                    .addComponent(wisValueLabel)
                    .addComponent(intValueLabel)
                    .addComponent(dexValueLabel)
                    .addComponent(strValueLabel)
                    .addComponent(conValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conStatLabel)
                    .addComponent(conValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strStatLabel)
                    .addComponent(strValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dexStatLabel)
                    .addComponent(dexValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wisValueLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wisStatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intStatLevel)
                    .addComponent(intValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(willValueLabel)
                    .addComponent(willStatLabel))
                .addContainerGap())
        );

        add(statsPanel, java.awt.BorderLayout.LINE_START);

        AdvancedInfoPanel.setBackground(new java.awt.Color(153, 153, 153));

        hitPointsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hitPointsLabel.setText("HP");

        hpValueLabel.setText("[val]");
        hpValueLabel.setToolTipText("Current HP of this character");

        speedLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        speedLabel.setText("Speed");

        speed_lightLoad.setText("[val]");
        speed_lightLoad.setToolTipText("light load");

        speed_mediumLoad.setText("[val]");
        speed_mediumLoad.setToolTipText("medium load");

        speed_heavyLoad.setText("[val]");
        speed_heavyLoad.setToolTipText("heavy load");

        carryCapacityLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        carryCapacityLabel.setText("Carry");

        carry_overHead.setText("[val]");
        carry_overHead.setToolTipText("lift over head");

        carry_offGround.setText("[val]");
        carry_offGround.setToolTipText("lift off ground");

        carry_pushDrag.setText("[val]");
        carry_pushDrag.setToolTipText("push or drag");

        hpMaxValueLabel.setText("[val]");
        hpMaxValueLabel.setToolTipText("Maximum HP of this character");

        javax.swing.GroupLayout AdvancedInfoPanelLayout = new javax.swing.GroupLayout(AdvancedInfoPanel);
        AdvancedInfoPanel.setLayout(AdvancedInfoPanelLayout);
        AdvancedInfoPanelLayout.setHorizontalGroup(
            AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedLabel)
                    .addComponent(carryCapacityLabel)
                    .addComponent(hitPointsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(carry_overHead)
                        .addComponent(speed_lightLoad))
                    .addComponent(hpValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdvancedInfoPanelLayout.createSequentialGroup()
                        .addComponent(carry_offGround)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carry_pushDrag))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdvancedInfoPanelLayout.createSequentialGroup()
                        .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hpMaxValueLabel)
                            .addComponent(speed_mediumLoad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speed_heavyLoad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdvancedInfoPanelLayout.setVerticalGroup(
            AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitPointsLabel)
                    .addComponent(hpValueLabel)
                    .addComponent(hpMaxValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLabel)
                    .addComponent(speed_lightLoad)
                    .addComponent(speed_mediumLoad)
                    .addComponent(speed_heavyLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdvancedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carryCapacityLabel)
                    .addComponent(carry_overHead)
                    .addComponent(carry_offGround)
                    .addComponent(carry_pushDrag))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        add(AdvancedInfoPanel, java.awt.BorderLayout.LINE_END);

        equipmentPanel.setPreferredSize(new java.awt.Dimension(375, 375));

        jLabel1.setText("Helmet");

        jLabel2.setText("Curiass");

        jLabel3.setText("Greaves");

        jLabel4.setText("Boots");

        jLabel5.setText("gloves");

        jLabel6.setText("Bracers");

        javax.swing.GroupLayout equipmentPanelLayout = new javax.swing.GroupLayout(equipmentPanel);
        equipmentPanel.setLayout(equipmentPanelLayout);
        equipmentPanelLayout.setHorizontalGroup(
            equipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(equipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(equipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(55, 55, 55))
        );
        equipmentPanelLayout.setVerticalGroup(
            equipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(equipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(equipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        add(equipmentPanel, java.awt.BorderLayout.CENTER);

        inventoryPanel.setBackground(new java.awt.Color(255, 255, 204));

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. On ground", "Item type", "Description", "No. On character"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(0).setResizable(false);
            itemTable.getColumnModel().getColumn(1).setResizable(false);
            itemTable.getColumnModel().getColumn(2).setResizable(false);
            itemTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(inventoryPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdvancedInfoPanel;
    private javax.swing.JLabel carryCapacityLabel;
    private javax.swing.JLabel carry_offGround;
    private javax.swing.JLabel carry_overHead;
    private javax.swing.JLabel carry_pushDrag;
    private javax.swing.JLabel conStatLabel;
    private javax.swing.JLabel conValueLabel;
    private javax.swing.JLabel dexStatLabel;
    private javax.swing.JLabel dexValueLabel;
    private javax.swing.JPanel equipmentPanel;
    private javax.swing.JLabel hitPointsLabel;
    private javax.swing.JLabel hpMaxValueLabel;
    private javax.swing.JLabel hpValueLabel;
    private javax.swing.JLabel intStatLevel;
    private javax.swing.JLabel intValueLabel;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JLabel speed_heavyLoad;
    private javax.swing.JLabel speed_lightLoad;
    private javax.swing.JLabel speed_mediumLoad;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel strStatLabel;
    private javax.swing.JLabel strValueLabel;
    private javax.swing.JLabel willStatLabel;
    private javax.swing.JLabel willValueLabel;
    private javax.swing.JLabel wisStatLabel;
    private javax.swing.JLabel wisValueLabel;
    // End of variables declaration//GEN-END:variables
}
