/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import threadWorkers.CharacterListCreator;
import world.World;

/**
 *
 * @author Robert
 */
public class MainMenu extends javax.swing.JPanel {
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    	charList.start();
    	charList.addPropertyChangeListener(new PropertyChangeListener() {
    		public void propertyChange(PropertyChangeEvent evt) {
    			characterList.setListData(charList.getArray());
    		}
    	});
    	//the CharacterListCreator will update the list on its own. It ^^^ has a handle to the characterList it's refreshing, so it can work on its own
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * Generated by NetBeans
     */
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServerList = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        characterList = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        newServerLocation = new javax.swing.JTextField();
        serverSelectionLabel = new javax.swing.JLabel();
        charaterListLabel = new javax.swing.JLabel();
        characterListRefreshButton = new javax.swing.JButton();
        beginTestWorldButton = new javax.swing.JButton();
        quitGameButton = new javax.swing.JButton();
        
        jButton1.setText("Join Game");

        jButton2.setText("Create Character");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCharacterButtonActionPerformed(evt);
            }
        });

        ServerList.setModel(new javax.swing.AbstractListModel<String>() {
			private static final long serialVersionUID = 1L;
			String[] strings = { "Loading saved servers" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ServerList);

        jButton3.setText("Options");

        characterList.setModel(new javax.swing.AbstractListModel<String>() {
			private static final long serialVersionUID = 1L;
			String[] strings = { "Loading - default text prior to proper function" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(characterList);

        jButton4.setText("Delete Character");

        newServerLocation.setText("Enter new Server IP & Port (ip:port)");
        newServerLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newServerLocationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newServerLocationFocusLost(evt);
            }
        });
        newServerLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newServerLocationActionPerformed(evt);
            }
        });

        serverSelectionLabel.setText("Select a Server");

        charaterListLabel.setText("Your Characters");

        characterListRefreshButton.setText("Refresh List");
        characterListRefreshButton.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				characterListRefreshButtonActionPerformed(arg0);
			}
        });

        beginTestWorldButton.setText("Offline Test World");
        beginTestWorldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginTestWorldButtonActionPerformed(evt);
            }
        });

        quitGameButton.setText("Quit");
        quitGameButton.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				quitGameButtonActionPerformed(arg0);
			}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitGameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(characterListRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(charaterListLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newServerLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addComponent(beginTestWorldButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(serverSelectionLabel)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serverSelectionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(charaterListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(characterListRefreshButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newServerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beginTestWorldButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(quitGameButton))
                .addContainerGap())
        );
    }

    private void createCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	//replaces this component with the CharacterCreator panel (as that is the requested view upon pressing the button that fires this event)
    	this.getParent().add(new CharacterCreator());
    	this.setVisible(false);
    	this.getParent().remove(this);
    }

    private void newServerLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newServerLocationActionPerformed
        // TODO add your handling code here:
    }

    private void newServerLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newServerLocationFocusGained
    	//when focus is gained, remove the default text (but only if it is the default. Otherwise, leave the existing text alone)
    	if(newServerLocation.getText().equals("Enter new Server IP & Port (ip:port)")){
    		newServerLocation.setText("");
    	}
    }

    private void newServerLocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newServerLocationFocusLost
    	//when focus is lost, check to see if it's empty. If so, replace it with the default.
    	if(newServerLocation.getText().isEmpty()){
    		newServerLocation.setText("Enter new Server IP & Port (ip:port)");
    	}
    }
    
    private void characterListRefreshButtonActionPerformed(ActionEvent evt){
    	//spawns a new thread to refresh the character list, and start it so that it may do so in parallel to other activities
    	charList.start();
    	//the CharacterListCreator will update the list on its own. It ^^^ has a handle to the characterList it's refreshing, so it can work on its own
    }

    private void beginTestWorldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginTestWorldButtonActionPerformed
    	//begin the test world
    	World world = new World(10, 10);
    	this.getParent().add(new GameViewPanel(world));
    	this.setVisible(false);
    	this.getParent().remove(this);
    }
    
    private void quitGameButtonActionPerformed(ActionEvent event){
    	System.exit(0);
    }
    
    private javax.swing.JList<String> characterList;
    private javax.swing.JList<String> ServerList;
    private javax.swing.JButton beginTestWorldButton;
    private javax.swing.JButton characterListRefreshButton;
    private javax.swing.JLabel charaterListLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField newServerLocation;
    private javax.swing.JButton quitGameButton;
    private javax.swing.JLabel serverSelectionLabel;
    
    private CharacterListCreator charList = new CharacterListCreator(characterList);
}
